[package]
name = "vonneumann"
version = "1.0.0"
edition = "2021"

keywords = ["executable", "memory", "windows", "unix"]
categories = ["memory-management", "no-std"]

description = "executable memory for windows and unix"
license = "MIT"
readme = "README.md"
repository = "https://github.com/jyn514/VonNeumann"

[dependencies]
libc = { version = "0.2" }
winapi = { version = "0.3", features = ["memoryapi", "winnt", "errhandlingapi", "sysinfoapi"] }

[dev-dependencies]
